version: "3"
services:
  front:
    image: node:14
    volumes:
      - ./front:/usr/src
      - front_modules:/usr/src/node_modules #node_modulesはコンテナ内部で用意します
    working_dir: "/usr/src"
    command: sh -c "yarn install && yarn start"
    ports:
      - "80:3000"
    environment:
      REACT_APP_SERVER_URL: "http://localhost:3000"
  api:
    image: python:3.9-buster
    ports:
      - "5000:5000"
    volumes:
    - ./api:/usr/src
    working_dir: "/usr/src"
    command: sh -c "pip install flask flask-sqlalchemy flask-script coverage && flask run --host=0.0.0.0 --port=5000"
    environment:
      FLASK_APP: "flask_blog"
      FLASK_ENV: "development"
volumes:
  front_modules:
